version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:15-alpine3.17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.0.9-alpine3.17
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 8s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    image: ghcr.io/while-act/hackathon-backend:latest
    restart: unless-stopped
    depends_on:
        redis:
          condition: service_healthy
        postgres:
          condition: service_healthy
    ports:
      - "3000:3000"
    environment:
        HOST: ${DOMAIN_NAME}
        EMAIL_USER: ${EMAIL_USER}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        EMAIL_STMP_HOST: ${EMAIL_STMP_HOST}
        EMAIL_PORT: ${EMAIL_PORT}
